apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          # - path: /posts
          #   backend:
          #     serviceName: query-clusterip-srv
          #     servicePort: 4002
          # - path: /posts/?(.*)/comments
          #   backend:
          #     serviceName: comments-clusterip-srv
          #     servicePort: 4001
          # - path: /?(.*)
          #   backend:
          #     serviceName: client-clusterip-srv
          #     servicePort: 3000
