apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          # imagePullPolicy: Never
          # image: us.gcr.io/ticketing-dev/auth
          image: xtophe02/ticket
          env:
            - name: MONGO_URI
              value: "mongodb://ticket-mongo-srv:27017/ticket"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-srv
spec:
  # type: NodePort
  selector:
    app: ticket
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: ticket
      # nodePort: 31515
